__title__ = "mathy_core"
__version__ = "0.7.21"
__summary__ = "mathy_core - Computer Algebra System for generating and manipulating expression trees from text inputs"
__uri__ = "https://mathy.ai"
__author__ = "Justin DuJardin"
__email__ = "justin@dujardinconsulting.com"
__license__ = "All rights reserved"
