# Project information
site_name: Mathy Core
site_description: Parse and manipulate math trees with interpretable rules
site_author: Justin DuJardin
site_url: https://core.mathy.ai

# Copyright
copyright: Copyright &copy; 2011 - 2024 Justin DuJardin

repo_name: mathy/mathy_core
repo_url: https://github.com/mathy/mathy_core
edit_uri: edit/master/website/docs/

google_analytics:
- UA-8701293-12
- auto

nav:
- Home: https://mathy.ai
- Core:
  - Home: index.md
  - Releases: changelog.md
  - License: license.md
  - API:
    - Expressions: api/expressions.md
    - Layout: api/layout.md
    - Parser: api/parser.md
    - Problems: api/problems.md
    - Rule: api/rule.md
    - Rules:
      - Associative Swap: api/rules/associative_swap.md
      - Balanced Move: api/rules/balanced_move.md
      - Commutative Swap: api/rules/commutative_swap.md
      - Constants Simplify: api/rules/constants_simplify.md
      - Distributive Factor Out: api/rules/distributive_factor_out.md
      - Distributive Multiply Across: api/rules/distributive_multiply_across.md
      - Multiplicative Inverse: api/rules/multiplicative_inverse.md
      - Restate Subtraction: api/rules/restate_subtraction.md
      - Variable Multiply: api/rules/variable_multiply.md
    - Testing: api/testing.md
    - Tokenizer: api/tokenizer.md
    - Tree: api/tree.md
    - Util: api/util.md
- Environments: https://envs.mathy.ai
extra:
  social:
  - icon: fontawesome/brands/github-alt
    link: https://github.com/justindujardin
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/justindujardin
  - icon: fontawesome/brands/linkedin
    link: https://linkedin.com/in/justindujardin

extra_css:
- lib/styles.css

extra_javascript:
- lib/termynal.js

theme:
  name: material
  icon:
    logo: material/hub
  features:
  - instant
  - navigation.sections
  - navigation.expand
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.footer
  - navigation.top
  - content.action.edit
  - content.action.view
  - content.tooltips
  favicon: img/favicon/favicon-16x16.png
  palette:
  - media: (prefers-color-scheme)
    primary: purple
    accent: deep-purple
    toggle:
      icon: material/brightness-auto
      name: Switch to light mode
  - media: '(prefers-color-scheme: light)'
    scheme: default
    primary: purple
    accent: deep-purple
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    primary: purple
    accent: deep-purple
    toggle:
      icon: material/brightness-4
      name: Switch to system preference

  highlightjs: true
  hljs_languages:
  - python
  - typescript
  - json
markdown_extensions:
- markdown.extensions.codehilite:
    guess_lang: false
- toc:
    permalink: true
- markdown_include.include:
    base_path: docs
- admonition
- codehilite
- extra
- pymdownx.superfences
- pymdownx.details

plugins:
- mathy
- search
- social
- git-revision-date-localized
- minify:
    minify_html: true
