name: Types

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11      
      - name: Setup Packages
        run: sh tools/setup.sh
      - name: Check for Type Errors
        run: sh tools/lint.sh
